"""Add comment, rating, and confirmed_by_user to Zayavka

Revision ID: 305367d373c0
Revises: 842bab39484d
Create Date: 2025-04-15 05:51:50.636881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305367d373c0'
down_revision = '842bab39484d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zayavka', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_by_user', sa.Boolean(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zayavka', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('confirmed_by_user')
        batch_op.drop_column('rating')
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
