"""Initial migration

Revision ID: 9dd6c118a9e9
Revises: 6f0aed922701
Create Date: 2025-04-22 15:55:48.311710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd6c118a9e9'
down_revision = '6f0aed922701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zayavka', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zayavka', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
